### ISSUE TITLE
Add option to populate remoteignore from gitignore?

### ISSUE THREAD

**Issue by sacsar** [remote-cli/remote#10]
It'd be handy if there was an option on `remote-init` to copy the contents of `.gitignore` to `.remoteignore`. An alternative would be to exclude gitignored files from the regular rsync (or add a setting in `.remote` to do it) and have an option to include those files in `remote-push`/`remote-pull`, as the one place I can think ignore them might be annoying is if you have editor configurations that you don't check in, but do want to keep in sync on both machines.

**Comment by shirshanka** [comment]
Yes I think this is indeed useful as a feature. 
There are pros and cons of doing this at time of remote-init versus as a "dynamic include" in the .remoteignore. 

I think for flexibility, keeping .remoteignore independent of .gitignore but allowing for the opportunity to seed it with .gitignore at remote-init time makes sense. 

A deeper dynamic integration would involve needing support for annotations in the .gitignore or the .svnignore for the directionality of the ignore... supports for overrides / exclusions in the .remoteignore... complexity that might be overkill.

**Comment by bzzzzzz** [comment]
https://github.com/remote-cli/remote/pull/19 should add simple .gitignore support

**Comment by bzzzzzz** [comment]
I'm closing this issue because the requested feature was added and documented. See `include_vsc_ignore_patterns` option description in the readme file for more details
