### ISSUE TITLE
Project-specific defaults for .remote.toml

### ISSUE THREAD

**Issue by pbsds** [remote-cli/remote#37]
Currently you can populate the ignore filter from `.gitignore`, but this would more often than not also ignore any `build/` folder which you rarely want to see on github, but do actually want to pull from the remote.

A current solution for pre-populating the ignore filter per project is to create a `.remote.toml` in the project with the `[push]`, `[pull]` and `[both]` already set, omitting `[[hosts]]`. This however creates the issue of `.remote.toml` now being tracked by git, a footgun which too often would lead to people committing their own hosts.

I therefore suggest adding support for one more file: `.remote-default.toml`. The intention is that `.remote-default.toml` is tracked by git while `.remote.toml` is not.  A tool to automatically generate a `.remote-default.toml` from the current `.remote.toml`, omitting the hosts, would also be nice

**Comment by bzzzzzz** [comment]
Hi. I agree that a separate file for just ignore patterns would be handy. I'll see if it is easy to implement when I have some spare time. If you want to prepare the PR with the feature yourself, I would appreciate it.

**Comment by shirshanka** [comment]
+100 from me for this feature. 
We actually had this ability before (.remote was host specific and .remoteignore was the file that could be checked-in for the repo).

**Comment by bzzzzzz** [comment]
This should be resolved by https://github.com/remote-cli/remote/pull/40. The additional settings file name is `.remoteignore.toml`
