### ISSUE TITLE
Shell escaping

### ISSUE THREAD

**Issue by pbsds** [remote-cli/remote#39]
See https://github.com/remote-cli/remote/blob/5d0fc94d9fba8d3a94cf3ba4a08db1a6d79d3108/src/remote/util.py#L242

It seems to only add `'` around arguments containing whitespace, but this does not account for shell escaping. 

* what if the argument contains a `'
* what if the argument contains a newline?

Python includes `shlex.quote` for this purpose.

It also seems to filter out empty arguments, which is odd, since `""` is a valid parameter for shell commands.

The environment arguments [could also be affected](https://github.com/remote-cli/remote/blob/e617e6307627cbc7eac7717528dbb0ef92b3dbe3/src/remote/workspace.py#L104)

**Comment by bzzzzzz** [comment]
Thanks for the suggestion! This issue should be resolved by https://github.com/remote-cli/remote/pull/40
