### ISSUE TITLE
Feature request: Support forwarding multiple ports

### ISSUE THREAD

**Issue by pbsds** [remote-cli/remote#41]
This is a great tool, and has been helpful in making remote work more streamlined.

From what i can see, `remote -tunnel a:b --tunnel c:d` only forwards `c:d`. When working with a remote jupyter notebook on my compute machine, I need both port 8888 for the notebook itself along with port 6006 for tensorboard.

A power user might also want some kind of range syntax, to forward anything between a range of ports. My bet is that `-tunnel a-b:c-d` could be a decent syntax for that.

While at it, perhaps the option to pass in raw `ssh -o` options could be added? This would allow companies with their infrastructure behind a firewall to use the `ProxyJump` option.

**Comment by bzzzzzz** [comment]
Hi, I understand your request, but I feel that we shouldn't overcomplicate remote's CLI parameters when there is a different tool available to achieve what you need. You can use `~/.ssh/config` to specify proxy/port forwarding parameters for your remote host:

```
Host your.remote.host
  LocalForward ...
  ProxyJump ...
```

You can see the configuration details here: http://www.manpagez.com/man/5/ssh_config/

**Comment by pbsds** [comment]
That is my current solution, and it works well for me. However it is not a portable solution. I made a PR

**Comment by bzzzzzz** [comment]
The latest version of remote is accessible via homebrew now
